var car = 'sabaru';
console.log("Is car == 'sabaru'? | Predict True");
console.log(car == 'sabaru');
console.log("Is car == 'ford'? | Predict True");
console.log(car == 'ford');
console.log("Is car != 'honda'? | Predict True");
console.log(car != 'honda');
console.log("Is car === 'sabaru'? | Predict True");
console.log(car === 'sabaru');
console.log("Is car !== 'sabaru'? | Predict True");
console.log(car !== 'sabaru');
console.log("Is car != 5? | Predict True");
console.log(car != '5');
console.log("Is car == 5? | Predict True");
console.log(car == '5');
console.log("Is car.length > 3? | Predict True");
console.log(car.length > 3);
console.log("Is car.length < 5? | Predict True");
console.log(car.length < 5);
console.log("Is car.charAt(0) == 's'? | Predict True");
console.log(car.charAt(0) == 's');
